steps:
- name: 'gcr.io/cloud-builders/bash'
  id: generate_version
  entrypoint: 'bash'
  args:
    - '-c'
    - |
      echo "Generating dynamic version..."
      DYNAMIC_VERSION="dev_$(date +%m%d%y)"
      echo "$DYNAMIC_VERSION" > /workspace/beat_version.txt
      echo "Generated version: $DYNAMIC_VERSION"

- name: 'gcr.io/cloud-builders/gcloud'
  id: fetch_artifactory_credentials
  entrypoint: 'sh'
  args:
    - '-c'
    - |
      echo "Fetching credentials..."
      echo -n "$(gcloud secrets versions access latest --secret=ARTIFACTORY_USER)" > /workspace/artifactory_user.txt
      echo -n "$(gcloud secrets versions access latest --secret=ARTIFACTORY_PASSWORD)" > /workspace/artifactory_password.txt

- name: 'gcr.io/cloud-builders/docker'
  id: authenticate_artifactory
  entrypoint: 'sh'
  args:
    - '-c'
    - |
      docker login logrhythm-docker.jfrog.io \
      --username "$(cat /workspace/artifactory_user.txt)" \
      --password-stdin < /workspace/artifactory_password.txt
  waitFor: 
    - fetch_artifactory_credentials

- name: 'gcr.io/cloud-builders/docker'
  id: build_beat
  entrypoint: 'bash'
  args:
    - '-c'
    - |
      DYNAMIC_VERSION=$(cat /workspace/beat_version.txt)
      echo "Using dynamic version: $DYNAMIC_VERSION"
      docker build \
        -f deploy/standard/Dockerfile \
        -t "logrhythm-docker.jfrog.io/${_BEAT_PUBLISHER}/collection/collection-dev/beats/${_BEAT_NAME}:$DYNAMIC_VERSION" \
        --build-arg BEAT_PUBLISHER=${_BEAT_PUBLISHER} \
        --build-arg BEAT_NAME=${_BEAT_NAME} \
        deploy
  waitFor:
    - authenticate_artifactory
    - generate_version

- name: 'gcr.io/cloud-builders/docker'
  id: push_dynamic_version
  entrypoint: 'bash'
  args:
    - '-c'
    - |
      DYNAMIC_VERSION=$(cat /workspace/beat_version.txt)
      docker push "logrhythm-docker.jfrog.io/${_BEAT_PUBLISHER}/collection/collection-dev/beats/${_BEAT_NAME}:$DYNAMIC_VERSION"
  waitFor:
    - build_beat

substitutions:
  _BEAT_PUBLISHER: 'logrhythm'
  _BEAT_NAME: 'pubsubbeat'

timeout: 2400s
options: 
  machineType: 'N1_HIGHCPU_8'
